/*
 * This file is autogenerated by autogen.pl. Do not edit this file by hand.
 */
#ifndef ORCM_FRAMEWORKS_H
#define ORCM_FRAMEWORKS_H

#include <opal/mca/base/mca_base_framework.h>

extern mca_base_framework_t orcm_cfgi_base_framework;
extern mca_base_framework_t orcm_notifier_base_framework;
extern mca_base_framework_t orcm_scd_base_framework;
extern mca_base_framework_t orcm_sensor_base_framework;
extern mca_base_framework_t orcm_sst_base_framework;

static mca_base_framework_t *orcm_frameworks[] = {
    &orcm_cfgi_base_framework,
    &orcm_notifier_base_framework,
    &orcm_scd_base_framework,
    &orcm_sensor_base_framework,
    &orcm_sst_base_framework,
    NULL
};

#endif /* ORCM_FRAMEWORKS_H */

