#
# Copyright (c) 2016 Intel, Inc. All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

SENSORPLUGIN=myplugin
PLUGINPREFIX=libudplugin_
CXX=g++
SENSYSPATH=/opt/openrcm
PLUGININSTALLPATH=$(SENSYSPATH)/lib/openmpi
CXXFLAGS=-O3 -fPIC -I$(SENSYSPATH)/include/openmpi
LDFLAGS=-L$(SENSYSPATH)/lib -shared -rdynamic -lsensysplugins

all:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) mysensor.cpp -o $(PLUGINPREFIX)$(SENSORPLUGIN).so
install: all
	install $(PLUGINPREFIX)$(SENSORPLUGIN).so $(PLUGININSTALLPATH)

clean:
	-rm *.so
